import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import { NavbarForSmScreens } from "@/components/NavbarForSmScreens";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

const FontDevWeb = localFont({
  src: "../fonts/conthrax-sb.otf",
  display: "swap",
  variable: "--font-dev-web",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${FontDevWeb.variable} `}>
        <Navbar />

        <NavbarForSmScreens />

        {children}

        <Footer />
      </body>
    </html>
  );
}
